export const ADD_ITEM_QUANTITY = 'cart/ADD_ITEM_QUANTITY'
export const SUBTRACT_ITEM_QUANTITY = 'cart/SUBTRACT_ITEM_QUANTITY'
export const REMOVE_CART_ITEM = 'cart/REMOVE_CART_ITEM'

export const ADD_PRODUCT_TO_CART = 'product/ADD_PRODUCT_TO_CART'
